### ISSUE TITLE
missing arguments in rand! methods for StaticArrays

### ISSUE THREAD

**Issue by schrimpf** [JuliaSIMD/VectorizedRNG.jl#27]
The `rand!` methods for StaticArrays beginning on [line 398 of api.jl](https://github.com/JuliaSIMD/VectorizedRNG.jl/blob/c34cf44b11711a8acbf2032ce6dde80f08f3871a/src/api.jl#L398) don't define  α,  β, and  γ, but use them in the call to `samplevector!`.

**Comment by chriselrod** [comment]
That's a definite bug.
Would you be willing to make a PR fixing that and adding tests by any chance?

**Comment by schrimpf** [comment]
Sure.
